[tool.tbump.version]
current = "3.0.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[tool.tbump.git]
message_template = "chore: bump to {new_version}"
tag_template = "{new_version}"

[[tool.tbump.file]]
src = "./VERSION"
search = "{current_version}"

[[tool.tbump.file]]
src = "./websearch-lib/src/main/elisp/websearch/websearch.el"
search = ";; Version: {current_version}"
